language: bash

services: 
    - docker

before_install:
  - |
      if git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '^(Dockerfile)'
      then
        echo "Only doc files were updated, not running the CI."
        exit
      fi

script: 
 - make dockerprod
